version: "3"
services:

  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
  
    ports:
      - "3306:3306"
    volumes:
      - ./dbvol:/var/lib/mysql

